#ddev-generated
# This configuration adds Tailscale routing capabilities to the web container.
web_extra_daemons:
  - name: tailscale-service
    command: tailscaled --statedir=${TS_STATE_DIR} --tun=userspace-networking 
    directory: /usr/sbin
  - name: "tailscale-router"
    command: tailscale up --authkey=$TS_AUTHKEY --hostname=$TS_HOSTNAME $TS_EXTRA_ARGS 
    directory: /var/www/html
  - name: "tailscale-daemon"
    command: /tailscale-router/tailscale-daemon.sh
    directory: /var/www/html