#ddev-generated
# This configuration adds Tailscale routing capabilities to the web container.
web_extra_daemons:
  - name: tailscale-service
    command: tailscaled --statedir=${TS_STATE_DIR:-/var/lib/tailscale} --tun=userspace-networking
    directory: /usr/sbin
  - name: "tailscale-router"
    command: tailscale up --auth-key=$TS_AUTHKEY --hostname=$DDEV_SITENAME $TS_EXTRA_ARGS
    directory: /var/www/html
  - name: "tailscale-certificates"
    command: bash -c 'tailscale cert --cert-file custom_certs/${DDEV_PROJECT}.crt --key-file custom_certs/${DDEV_PROJECT}.key $(tailscale status --peers=false --json | jq -r ".Self.DNSName" | sed "s/\.$//")'
    directory: /var/www/html/.ddev
  - name: "tailscale-serve"
    command: bash -c 'tailscale serve $(tailscale status --peers=false --json | jq -r ".Self.DNSName" | sed "s/\.$//"):$DDEV_HOST_PORT_HTTP'
    directory: /var/www/html/.ddev